---

- name: create_nfs_directory
  ansible.builtin.file:
    path: /srv/nfs
    state: directory
    mode: '0755'

- name: mount_volume
  mount:
    path: /srv/nfs
    src: "/dev/{{volume_group}}/{{logical_volume}}"
    state: mounted
    fstype: xfs
  register: outputvol