---

- name: start_firewall
  systemd:
    name: firewalld
    state: started

- name: add_firewall_nfs
  firewalld:
    service: nfs
    permanent: yes
    state: enabled

- name: add_firewall_rpc
  firewalld:
    service: rpc-bind
    permanent: yes
    state: enabled

- name: add_firewall_mountd
  firewalld:
    service: mountd
    permanent: yes
    state: enabled

- name: reload_firewall
  systemd:
    name: firewalld
    state: reloaded