---

- name: calculate_swap
  shell : free -m | grep Swap | awk '{print $2}'
  register: swap_used

- name: disable_swap
  shell: "swapoff --all"
  when: (swap_used.stdout_lines[0] | int) > 0

- name: disable_swap_permanently
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: (swap_used.stdout_lines[0] | int) > 0