---

- name: add_port_firewall_nfs
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
  loop: "{{ports_master_node}}"

- name: reload_firewall
  systemd:
    name: firewalld
    state: reloaded