---
- name: Master
  hosts: master
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Configurando Workers
  hosts: workers
  vars_files:
  - "group_vars/vars.yaml"
  gather_facts: false
  become: yes
  tasks:
  - name: join_workers_to_master
    shell: "{{hostvars[item].join_command}}"
    register: commmand_join
    loop: "{{ query('inventory_hostnames', 'master') }}"

  - name: add_ports
    firewalld:
      zone: public
      permanent: yes
      port: "{{item}}"
      state: enabled
    loop: "{{ports_worker_node}}"

  - name: reload_firewall
    systemd:
      name: firewalld
      state: reloaded